# Para las implementaciones del DAO
DAO.usuario=hibernate
DAO.metodoOperacion=hibernate
DAO.categoriaConcepto=hibernate
DAO.venta=hibernate
DAO.compra=hibernate
DAO.gasto=hibernate
DAO.otroIngreso=hibernate
DAO.otroEgreso=hibernate
DAO.configuracion=hibernate
DAO.vencimiento=hibernate
