# Para las implementaciones del DAO
DAO.usuario=hibernate
DAO.metodoOperacion=hibernate
DAO.categoriaConcepto=hibernate
DAO.venta=hibernate
DAO.compra=hibernate
DAO.gasto=hibernate
DAO.otroIngreso=hibernate
DAO.otroEgreso=hibernate
DAO.configuracion=hibernate
DAO.vencimiento=hibernate

#Para la conexion a la base de datos
connection.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
connection.host=localhost
connection.port=1433
connection.database=GestionFinancieraDB
connection.user=sa
connection.password=1234
connection.encrypt=true
connection.trustServerCertificate=true
